FROM node:22-alpine3.19 AS build

WORKDIR /app

COPY package*.json ./
RUN npm ci --omit=dev

RUN npm install rollup

COPY . .

ENV NODE_ENV=production

RUN npm run build

FROM node:22-alpine3.19 AS production

WORKDIR /app

COPY --from=build /app ./

EXPOSE 3000

CMD ["node", "build"]

# CMD ["node", "-r", "dotenv/config", "build"]